Sheet types addGlobals and adjusted imports
saulpw/visidata pull request #1228
Opened 2021-12-03 18:11 UTC by geekscrapy

The initial reason for this PR was adding CsvSheet to global.

Also modified other loaders to not use import * syntax, and add similar other sheet types to global using addGlobal.

I can continue to do this for the other loaders if you want it uniform across all loaders, but I thought I'd just do a few to give an example of what it might look like, to see if you want it done across them all.

Personally, I see it as beneficial as all Sheet types should be as accessible as the next.

If it doesn't suit you, then that's fine, it was a good exercise!

2021-12-03 18:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/saulpw/visidata?pullRequest=1228) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/saulpw/visidata?pullRequest=1228) before we can accept your contribution.<br/><hr/>**Funvacuum** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/saulpw/visidata?pullRequest=1228) it.</sub>

2021-12-04 06:13 UTC, saulpw requested changes
Thanks for putting this together, @geekscrapy!  It's great to clean up the imports, and expose some of these Sheet types.  I have a few notes:
- I don't want to have to adhere to the internals of the loaders, so I'm hesitant to expose more than we need to.  If a sheet type is useful (either to inherit from, or instantiate in some other way), then let's definitely expose it, but I'm not sure if we need to expose every sheet type automatically.  I could be convinced though.
- be careful when converting global `options` to `vd.options`.  The usages may be equivalent in most cases, but sometimes the global should actually be a sheet-specific option.  `vd.options` indicates that there's no way it could be a sheet-specific option, either because it doesn't make sense, or there is no relevant sheet in that context.  This may or may not be true; for example, `options.html_title` should probably be `sheet.options` instead of `vd.options`.  Or maybe `vsheets[0]`, as we might be converging on a rule of "multi-sheet save takes options from the first sheet".  So they each have to be considered.
- Keep the final newline at the end of the file (probably an editor or git setting).
- Don't add/remove independent blocks of whitespace unless we're adhering to a standard (which we haven't set yet).

So we should at least fix the two bugs you found though (in separate commits), and I'd like to at least keep the import cleanups you've made.  Let's think about each of the options and globals separately, though we can add CsvSheet to globals too (and could you make a separate commit from the import changes?).

2021-12-04 06:13 UTC, saulpw commented on visidata/loaders/fixed_width.py
> +                fp.write('%s\n\n' % sheet.name)
Nice find!  Let's put this in a separate PR.

2021-12-04 06:13 UTC, saulpw commented on visidata/loaders/eml.py
> +        vd.execAsync(sheet.extract_part, givenpath, parts[0])
Another good catch!  separate commit at least though.

2021-12-04 07:50 UTC, geekscrapy commented
No problem with all the above.

I'll close this and do some separate PRs based on the themes you set above 👍

In regards to the points above (in order)

- I presume you are referring to only exposing what is required? Yes, totally understandable, however my opinions would be that 1. When you want it, it's not there 2. All sheet types should be exposed the same?
- 👍 I actually tried to do `from visidata import options` but it gave me a recursion error regarding imports. I'll make a separate PR for this and each can be taken on their own merits.

2021-12-04 07:50 UTC, closed without merging