Index columns
saulpw/visidata pull request #1361
Opened 2022-04-25 22:43 UTC by anjakefala

* set .vdj to be the default CmdLog save format
* in the *CmdLog* type **col** indices as `int`, and **col** names as `str`.

since 6e1334167f740a78832054e63020215acc6d5a88, the type of the *col* attribute matters.
If replaying, and *col* is an `int`, the CmdLog will index by position.
If *col* is a `str` it will index by column name.

Closes #1349

2022-04-30 03:14 UTC, saulpw commented on visidata/cmdlog.py
> +        colname = str(sheet.cursorCol.name) or int(sheet.visibleCols.index(sheet.cursorCol))
These type coercions should not be necessary; `index()` should return an int, and the column name should be a string already.

2022-04-30 03:15 UTC, saulpw requested changes
One small change and then should be good to go!  Thanks @anjakefala.

2022-05-01 04:52 UTC, merged

2022-05-07 18:13 UTC, frosencrantz commented
This looks really great @anjakefala! 

I have existing .vd files.  What is the best way to convert these files to the new .vdj format?

2022-05-07 19:46 UTC, anjakefala commented
`vd -b foo.vd -o foo.vd`!

Or `vd -p foo.vd`.
Then `Ctrl+D` *foo.vdj*. =) I would use the cutting edge on `develop`.

2022-05-08 21:09 UTC, frosencrantz commented
Great!  Will try that.  And thanks for making this change.