Improve GeoJSON functionality
saulpw/visidata pull request #1477
Opened 2022-08-12 15:59 UTC by mwayne

These changes:

- Fix saving and plotting GeoJSON files
- Add support for adding, editing, or removing feature properties
- Includes a test to confirm basic feature manipulations are present in a saved geojson file

I've copied the json loader's `_rowdict` function, but I'm happy to refactor if you have a different way you'd like to handle that.

2022-08-12 15:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/saulpw/visidata?pullRequest=1477) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/saulpw/visidata?pullRequest=1477) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/saulpw/visidata?pullRequest=1477) it.</sub>

2022-08-12 22:59 UTC, saulpw commented on visidata/loaders/geojson.py
> +                        c = GeoJSONColumn(name=prop, prop=prop)
VisiData typically uses `expr` for things like this, so that it's consistently editable on the Columns Sheet.

2022-08-12 23:01 UTC, saulpw requested changes
Hey @mwayne, this looks great, thanks for your diligence and effort!  If you can change `prop` to `expr` as suggested, then we can ask @anjakefala to give it a once-over and look through your test, and then I'm happy to merge it.

2022-08-14 03:55 UTC, anjakefala commented
This PR has my seal of approval!

2022-08-14 03:56 UTC, anjakefala commented on tests/golden/save-geojson.geojson
> +{"type": "FeatureCollection", "features": [{"geometry": {"type": "Polygon", "coordinates": [[[-117.215796, 32.72734], [-117.213956, 32.728308], [-117.20961, 32.72839], [-117.209362, 32.729376], [-117
Thanks for paying careful attention to the name of your test! =)

2022-08-14 04:59 UTC, merged