[sheets] fix reload() for tsv sheets with key columns
saulpw/visidata pull request #1997
Opened 2023-08-14 03:55 UTC by midichef

When viewing a TSV sheet that has a key column, `reload` adds empty columns to the sheet. The more rows the sheet has, the more columns are added. This can be seen with `seq 5 |vd -f tsv`

The reason is that `TsvSheet.iterload()` extends each row horizontally, to match its length to the number of visible columns:
https://github.com/saulpw/visidata/blob/4ffacbb2ab7b79029bd7304eff0c317e9c009027/visidata/loaders/tsv.py#L88

Its count of visible columns is too high, because it relies on a value `self.keyCols` that is cached but incorrect. After `SequenceSheet.setCols()` it should be zero:
https://github.com/saulpw/visidata/blob/4ffacbb2ab7b79029bd7304eff0c317e9c009027/visidata/sheets.py#L355

This PR clears the cache after `setCols()` so that `keyCols` and `nVisibleCols` will be correct.

2023-08-14 04:24 UTC, saulpw requested changes
Thanks for the fix, @midichef!  Let's put this inside `setCols()` instead so that other subclasses who reimplement `reload()` can avoid this issue.

I'm also wondering about putting a `#1997` on this line.  It's a bit of clutter but some part of me wants to see the code littered with these tiny notations of the bugfixes, so we can see at a glance where the battle scars are, and to avoid regressions if the function ever gets rewritten.  Thoughts?

2023-08-16 23:19 UTC, saulpw approved these changes

2023-08-16 23:19 UTC, merged

2023-08-17 01:02 UTC, midichef commented
Yup, that makes sense.

But it looks like the github tests are failing. I'm not seeing these errors on my local machine.

2023-08-17 05:17 UTC, anjakefala commented
@midichef Seperate issue related to a seperate commit! Looking into it now. =)