[graph-] fix to implement color_graph_refline option
saulpw/visidata pull request #2569
Opened 2024-10-16 06:22 UTC by midichef

Closes #2566.

2024-10-16 07:39 UTC, saulpw approved these changes

2024-10-16 07:48 UTC, saulpw requested changes
Let's either change the option name itself to color_refline, or add an optalias in deprecated.py.  It's minor but I'd like to encourage a habit of maintaining compatibility, at least when it's easy :)

2024-10-17 08:45 UTC, midichef commented
> Let's either change the option name itself to color_refline, or add an optalias in deprecated.py.

I added an optalias, and left the preferred name as`color_graph_refline`. That way the prefix is the same as the existing `color_graph_*` option `color_graph_axis`.

2024-10-17 16:08 UTC, saulpw approved these changes
Thanks, @midichef!

2024-10-17 17:00 UTC, merged