Add conll loader to plugins file
saulpw/visidata pull request #772
Opened 2020-11-09 13:37 UTC by polm

This is following up on #769. The plugin appears to be working so I think it's good for an initial release, let me know if anything else is necessary.

2020-11-10 00:17 UTC, anjakefala commented
Thanks! :blush: 

Could you please place a small sample conll dataset in your plugin's repo? =)

2020-11-10 05:17 UTC, polm commented
Got it, I added a sample data file and `output.jsonl`. Let me know if there's anything else I should do.

2020-11-11 21:13 UTC, anjakefala commented on plugins/plugins.jsonl
> +{"name":"conll", "description":"CoNLL data loader", "maintainer": "Paul McCann <polm@dampfkraft.com>", "latest_release": "2020-11-09", "latest_ver": "0.1.0", "url": "https://github.com/polm/visidata-
`url` needs to point to the raw text on a specific commit! This usl is what is used to download the file.

E.g. https://raw.githubusercontent.com/polm/visidata-conll/a11ffa99fe497b83c522bef86d89b246b2a8d6e0/conll.py

2020-11-11 21:19 UTC, anjakefala requested changes
The `url` in the jsonl needs to point to a specific commit of `conll.py` (see my comment).

Once that is taken care of, I will merge this in, and deploy it. =) This is really cool, thank you for contributing!

**Edit**: I originally had a comment that `conll.py` needs a `vd.addGlobals(globals())`. This is in motion to be deprecated. But, I just checked, and the alternative (using `@VisiData.api`) does not neatly work for plugins, yet. It would probably be best if you add `vd.addGlobals(globals())` for now, so that your plugin works for VisiData v2.0. If you do not add it, your plugin would still be loaded if someone manually wrote `from plugins.conll import *`, but would not if someone used `import plugins.conll`.

2020-11-12 03:45 UTC, polm commented
Thanks for the comments, I pushed the changes as described. 

Also thanks for the clarification about `addGlobals`, I had thought that wasn't needed if the decorator was used.

2020-11-12 03:51 UTC, anjakefala approved these changes
Awesome! Thank you! =)

`addGlobals()` will not be needed in v2.1 ^^

2020-11-12 03:51 UTC, merged